---
title: "sketches"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

# Read in data

```{r}
data <- readxl::read_excel("../Award-CIP4-Sex-RaceEth.xlsx") %>%
# data <- readxl::read_excel("../Award-CIP2-Sex-RaceEth.xlsx") %>%
  select(-`[Institution Name]`) %>% 
  rename(
    CRED = `[Award Level Code]`,
    CIP4 = `[CIP Code and Description (4 digit)]`,
    # CIP2 = `[CIP Code and Description (2 digit)]`,
    race_eth = `[Race and Ethnicity]`,
    sex = `[Sex]`    
  ) %>% 
  gather(year, count, `2017`:`1997`) %>% 
  mutate(
    count = as.numeric(count),
    year = as.numeric(year)
  )

AGGREGATE_STR <- "Total for selected values"

get_top_fields <- function(top_n, cond = TRUE, narm = TRUE) {
  data %>%
    filter_(cond) %>% 
    filter(CIP4 != AGGREGATE_STR) %>%
    group_by(CIP4) %>%
    summarize(total = sum(count, na.rm = narm)) %>%
    arrange(-total) %>% 
    head(top_n) %>% 
    pull(CIP4)
}
```

# Bachelors completions

```{r}
data %>%
  filter(CIP4 != AGGREGATE_STR) %>%
  filter(sex == AGGREGATE_STR & race_eth == AGGREGATE_STR) %>% 
  filter(CRED == "Bachelor's degree") %>%
  # filter(CIP4 %in% get_top_fields(20, quote(CRED == "Bachelor's degree"), FALSE)) %>%
  mutate(CIP4 = factor(CIP4, levels = get_top_fields(1000, quote(CRED == "Bachelor's degree")))) %>% 
  filter(CIP4 %in% get_top_fields(25, quote(CRED == "Bachelor's degree"))) %>% 
  ggplot(aes(year, count)) +
  geom_line() +
  facet_wrap(~ CIP4) +
  expand_limits(y = 0) +
  theme(
    strip.background = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major.y = element_line(colour = "grey90")
  )

data %>%
  filter(sex == AGGREGATE_STR & race_eth == AGGREGATE_STR) %>% 
  filter(CRED == "Bachelor's degree") %>%
  filter(year == 2017) %>% 
  arrange(-count)
```


# Preliminary sketches

```{r}
data %>% 
  filter(sex != AGGREGATE_STR & race_eth == AGGREGATE_STR) %>% 
  filter(CRED == "Doctor's degree - research/scholarship") %>%
  ggplot(aes(year, count, color = sex)) +
  geom_line() +
  facet_wrap(~ CIP4, scales = "free_y") +
  theme(
    strip.background = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major.y = element_line(colour = "grey90")
  )

data %>% 
  filter(race_eth != AGGREGATE_STR) %>% 
  filter(CRED == "Bachelor's degree") %>%
  filter(CIP4 %in% get_top_fields(100, quote(CRED == "Master's degree"), FALSE)) %>%
  mutate(CIP4 = factor(CIP4, get_top_fields(100, quote(CRED == "Master's degree"), FALSE))) %>% 
  ggplot(aes(year, count, color = race_eth)) +
  geom_line() +
  facet_grid(CIP4 ~ sex, scales = "free_y") 
  theme(
    strip.background = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major.y = element_line(colour = "grey90")
  )
```
